In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentence
sent=['the glass of milk',
      'the glass off juice',
      'the cup of tea',
      'I am good boy',
      'I am a good developer',
      'understanding the meaning of words',
      'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass off juice',
 'the cup of tea',
 'I am good boy',
 'I am a good developer',
 'understanding the meaning of words',
 'your videos are good']

In [21]:
# define vocbulary size
voc_size = 10000

In [22]:
## One_hot_representation
onehot_rep = [one_hot(words,voc_size) for words in sent]
onehot_rep

[[3803, 6230, 4537, 4889],
 [3803, 6230, 4603, 6802],
 [3803, 460, 4537, 5463],
 [6949, 371, 4187, 152],
 [6949, 371, 3436, 4187, 1150],
 [9949, 3803, 8648, 4537, 9950],
 [3233, 7039, 2171, 4187]]

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [24]:
sent_length=8
emb_doc = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(emb_doc)

[[   0    0    0    0 3803 6230 4537 4889]
 [   0    0    0    0 3803 6230 4603 6802]
 [   0    0    0    0 3803  460 4537 5463]
 [   0    0    0    0 6949  371 4187  152]
 [   0    0    0 6949  371 3436 4187 1150]
 [   0    0    0 9949 3803 8648 4537 9950]
 [   0    0    0    0 3233 7039 2171 4187]]


In [36]:
voc_size = 10000  # Example vocabulary size (should be >0)
dim = 10        # Example embedding dimension (should be >0)
sent_length = 8 # Example sentence length

model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')


In [38]:
import numpy as np

# dummy_input = np.random.randint(0, voc_size, (1, sent_length))
# model.predict(dummy_input)  # Force building of the model
model.summary()


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.predict(emb_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[[-3.79482992e-02,  1.98984034e-02, -3.15943249e-02,
         -1.42782554e-02, -3.05977948e-02,  1.62535571e-02,
         -1.18309744e-02, -2.07685716e-02,  4.21753414e-02,
         -7.67188147e-03],
        [-3.79482992e-02,  1.98984034e-02, -3.15943249e-02,
         -1.42782554e-02, -3.05977948e-02,  1.62535571e-02,
         -1.18309744e-02, -2.07685716e-02,  4.21753414e-02,
         -7.67188147e-03],
        [-3.79482992e-02,  1.98984034e-02, -3.15943249e-02,
         -1.42782554e-02, -3.05977948e-02,  1.62535571e-02,
         -1.18309744e-02, -2.07685716e-02,  4.21753414e-02,
         -7.67188147e-03],
        [-3.79482992e-02,  1.98984034e-02, -3.15943249e-02,
         -1.42782554e-02, -3.05977948e-02,  1.62535571e-02,
         -1.18309744e-02, -2.07685716e-02,  4.21753414e-02,
         -7.67188147e-03],
        [-3.74435410e-02,  2.76372321e-02,  3.85347866e-02,
          3.59965079e-02, -4.35768478e-02, -1.39911547e-02,
         -2.95542181e-04,  4.88021411e-02,  1.264933